version: '3.8'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: "zookeeper"
    ports:
    - 2181:2181
    # volumes:
    # - ./zookeeper:/var/lib/zookeeper
    networks:
      - kafka_network
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    container_name: "kafka"
    ports:
      - 9092:9092
    # volumes:
    # - ./kafka:/opt/bitnami/kafka
    restart: unless-stopped
    depends_on:
    - zookeeper
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_LISTENERS=PLAINTEXT://:9092
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    - KAFKA_RESTART_ATTEMPTS=10
    - KAFKA_RESTART_DELAY=5
    # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    - ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL=0
    networks:
      - kafka_network
networks:
  kafka_network:
    external: true